#pragma once

#define SD_DRIVE        "sdmc"
#define ROOT_FOLDER SD_DRIVE ":/Orichi"
#define LOG_FILE         ROOT_FOLDER "/log.txt"
#define MAIN_SCRIPT      ROOT_FOLDER "/main.lua"
#define CONTROL_SCRIPT   ROOT_FOLDER "/control.lua"
#define ANIM_SCRIPT      ROOT_FOLDER "/anim.lua"
#define CUES00_SCRIPT    ROOT_FOLDER "/cues00.lua"
#define CUES01_SCRIPT    ROOT_FOLDER "/cues01.lua"
#define CUES02_SCRIPT    ROOT_FOLDER "/cues02.lua"
#define CUES03_SCRIPT    ROOT_FOLDER "/cues03.lua"
#define CUES04_SCRIPT    ROOT_FOLDER "/cues04.lua"
#define CUES05_SCRIPT    ROOT_FOLDER "/cues05.lua"
#define CUES06_SCRIPT    ROOT_FOLDER "/cues06.lua"
#define CUES07_SCRIPT    ROOT_FOLDER "/cues07.lua"
